"""Repository Protocol definitions.

Defines ``typing.Protocol`` interfaces for each repository so that:
- Routers depend on the protocol (not the concrete class)
- Tests can easily swap in mocks/stubs
- The type checker can verify implementations
"""

from typing import List, Optional, Protocol

from core.entities.models import (
    Atendimento,
    AtendimentoCreate,
    AtendimentoFilter,
    AtendimentoUpdate,
    Arquivo,
    AuditoriaEntry,
    DashboardStats,
    Documento,
    DocumentoCreate,
    Nota,
    NotaCreate,
)


class AuditoriaRepoProtocol(Protocol):
    def registrar(self, acao: str, entidade: str, entidade_id: Optional[int], detalhes: Optional[str], usuario: Optional[str] = ...) -> None: ...
    def listar(self, limit: int = ...) -> List[AuditoriaEntry]: ...


class AtendimentoRepoProtocol(Protocol):
    def list_all(self, filters: Optional[AtendimentoFilter] = ...) -> List[Atendimento]: ...
    def count(self, filters: Optional[AtendimentoFilter] = ...) -> int: ...
    def get_by_id(self, id: int) -> Optional[Atendimento]: ...
    def create(self, data: AtendimentoCreate) -> Optional[int]: ...
    def update(self, id: int, data: AtendimentoUpdate) -> bool: ...
    def delete(self, id: int) -> bool: ...
    def get_stats(self) -> DashboardStats: ...
    def list_pacientes_resumo(self, q: Optional[str] = ..., limit: int = ..., offset: int = ...) -> list: ...


class ArquivoRepoProtocol(Protocol):
    def list_all(self) -> List[Arquivo]: ...
    def save(self, filename: str, content: bytes, content_type: str = ...) -> Optional[int]: ...
    def get_by_id(self, id: int) -> Optional[Arquivo]: ...
    def delete(self, id: int) -> bool: ...


class DocumentoRepoProtocol(Protocol):
    def list_all(self) -> List[Documento]: ...
    def create(self, data: DocumentoCreate) -> Optional[int]: ...
    def find_by_atendimento(self, atendimento_id: int) -> Optional[Documento]: ...
    def delete(self, id: int) -> bool: ...


class PreferencesRepoProtocol(Protocol):
    def get(self, key: str, default: Optional[str] = ...) -> Optional[str]: ...
    def get_many(self, prefix: str) -> dict: ...
    def get_many_keys(self, keys: list) -> dict: ...
    def save(self, key: str, value: str) -> bool: ...
    def delete(self, key: str) -> bool: ...


class TemporaryPermissionRepoProtocol(Protocol):
    def create(self, google_doc_id: str, permission_id: str, created_by: Optional[str], expires_at: Optional[str]) -> Optional[int]: ...
    def list_expired(self) -> list: ...
    def mark_revoked(self, perm_id: int) -> bool: ...


class UserRepoProtocol(Protocol):
    def find_by_username(self, username: str): ...
    def create(self, data): ...
    def update(self, user_id: int, data): ...
    def delete(self, user_id: int) -> bool: ...
    def list_all(self) -> list: ...


class ClinicConfigRepoProtocol(Protocol):
    def get_all_clinic_data(self) -> dict: ...
    def save_clinic_data(self, data: dict) -> bool: ...
    def save(self, key: str, value: str) -> bool: ...
